import PDFDocument from "pdfkit";
export const CreatePdf = async (data) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margin: 50,
      info: {
        Author: "CortexAI",
        Title: data.title,
        Creator: "CortexAI",
      },
    });

    const chunks = [];
    // dekh pdf directly nhi create hoga
    // sabse pehle tu title daalega,subtitle dalega fir content so
    // inc chunk we ill import all things
    // so we will push all that in chunks array and later will concat and store in s3
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => {
      resolve(Buffer.concat(chunks));
    });
    doc.on("error", () => reject);

    doc
      .fontSize(28)
      .text(data.title, {
        align: "center",
      })
      .fillColor("#111827");

    if (data.subtitle) {
      doc.moveDown(0.5);
    }

    doc
      .fontSize(12)
      .text(data.subtitle, {
        align: "center",
      })
      .fillColor("#6B7280");

    doc.moveDown(2);

    data?.sections?.forEach((s) => {
      doc.fontSize(18).text(s.heading).fillColor("#111827");

      doc.moveDown(0.5);

      s?.points?.forEach((p) => {
        doc
          .fontSize(12)
          .text("•" + p, {
            lineGap: 2,
          })
          .fillColor("#374151");
      });

      doc.moveDown();
    });

    doc.moveDown();

    doc
      .fontSize(10)
      .text("Generated By CortexAI", {
        align: "center",
      })
      .fillColor("#9CA3AF");

      doc.end()
  });
};
